# Project: Projectdelet
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = maindelet.o
LINKOBJ  = maindelet.o
LIBS     = -L"E:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -mwindows -m32 -g3
INCS     = -I"E:/Software/Dev-Cpp/MinGW64/include" -I"E:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Software/Dev-Cpp/MinGW64/include" -I"E:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Projectdelet.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

maindelet.o: maindelet.cpp
	$(CPP) -c maindelet.cpp -o maindelet.o $(CXXFLAGS)
